// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Monkey.WebApi.AcceptanceTests.Integration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ControllerInvocations")]
    public partial class ControllerInvocationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ControllerInvocations.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ControllerInvocations", "\tIn order to avoid silly mistakes\r\n\tAs a web-api developer\r\n\tI want to be be sure" +
                    " that controllers invoke command/query handlers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("The applications container is configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can invoke create command handler on dynamic controller")]
        public virtual void ICanInvokeCreateCommandHandlerOnDynamicController()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can invoke create command handler on dynamic controller", null, ((string[])(null)));
#line 10
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Code"});
            table1.AddRow(new string[] {
                        "1",
                        "public class CreateUser { public string Name { get;set; }}"});
            table1.AddRow(new string[] {
                        "2",
                        "public class UserEntity { public Guid Id { get; set; } public string Name { get; " +
                            "set; }}"});
#line 11
 testRunner.Given("I have written command \'CreateUser\' and result as:", ((string)(null)), table1, "Given ");
#line 15
 testRunner.And("I have written command-handler that accepts \'CreateUser\' and returns \'UserEntity\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table2.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 16
 testRunner.When("I invoke \'UserController\' with \'Post\' method and \'CreateUserRequest\' argument:", ((string)(null)), table2, "When ");
#line 19
 testRunner.Then("CommandHandler is invoked with corresponding \'CreateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can invoke custom command handler on dynamic controller with no resource id")]
        public virtual void ICanInvokeCustomCommandHandlerOnDynamicControllerWithNoResourceId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can invoke custom command handler on dynamic controller with no resource id", null, ((string[])(null)));
#line 22
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Code"});
            table3.AddRow(new string[] {
                        "1",
                        "public class ActivateUser { public string Name { get;set; }}"});
            table3.AddRow(new string[] {
                        "2",
                        "public class UserEntity { public Guid Id { get; set; } public string Name { get; " +
                            "set; }}"});
#line 23
 testRunner.Given("I have written command \'ActivateUser\' and result as:", ((string)(null)), table3, "Given ");
#line 27
 testRunner.And("I have written command-handler that accepts \'ActivateUser\' and returns \'UserEntit" +
                    "y\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table4.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 28
 testRunner.When("I invoke \'UserController\' with \'Activate\' method and \'ActivateUserRequest\' argume" +
                    "nt:", ((string)(null)), table4, "When ");
#line 31
 testRunner.Then("CommandHandler is invoked with corresponding \'ActivateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can invoke update command handler on dynamic controller")]
        public virtual void ICanInvokeUpdateCommandHandlerOnDynamicController()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can invoke update command handler on dynamic controller", null, ((string[])(null)));
#line 35
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Code"});
            table5.AddRow(new string[] {
                        "1",
                        "public class UpdateUser { public string Name { get;set; } public Guid Id {get; se" +
                            "t; }}"});
            table5.AddRow(new string[] {
                        "2",
                        "public class UserEntity { public Guid Id { get; set; } public string Name { get; " +
                            "set; }}"});
#line 36
 testRunner.Given("I have written command \'UpdateUser\' and result as:", ((string)(null)), table5, "Given ");
#line 40
 testRunner.And("I have written command-handler that accepts \'UpdateUser\' and returns \'UserEntity\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.When("I found record with id to update", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table6.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 42
 testRunner.And("I invoke \'UserController\' with \'Put\' method and \'UpdateUserRequest\' argument:", ((string)(null)), table6, "And ");
#line 45
 testRunner.Then("CommandHandler is invoked with corresponding \'UpdateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can invoke custom command handler on dynamic controller")]
        public virtual void ICanInvokeCustomCommandHandlerOnDynamicController()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can invoke custom command handler on dynamic controller", null, ((string[])(null)));
#line 48
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Code"});
            table7.AddRow(new string[] {
                        "1",
                        "public class ActivateUser { public string Name { get;set; } public Guid Id {get; " +
                            "set; }}"});
            table7.AddRow(new string[] {
                        "2",
                        "public class UserEntity { public Guid Id { get; set; } public string Name { get; " +
                            "set; }}"});
#line 49
 testRunner.Given("I have written command \'ActivateUser\' and result as:", ((string)(null)), table7, "Given ");
#line 53
 testRunner.And("I have written command-handler that accepts \'ActivateUser\' and returns \'UserEntit" +
                    "y\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I found record with id to update", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table8.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 55
 testRunner.And("I invoke \'UserController\' with \'Activate\' method and \'ActivateUserRequest\' argume" +
                    "nt:", ((string)(null)), table8, "And ");
#line 58
 testRunner.Then("CommandHandler is invoked with corresponding \'ActivateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can have many actions on one dynamic controller")]
        public virtual void ICanHaveManyActionsOnOneDynamicController()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can have many actions on one dynamic controller", null, ((string[])(null)));
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Code"});
            table9.AddRow(new string[] {
                        "1",
                        "public class ActivateUser { public string Name { get;set; } public Guid Id {get; " +
                            "set; }}"});
            table9.AddRow(new string[] {
                        "2",
                        "public class UserEntity { public Guid Id { get; set; } public string Name { get; " +
                            "set; }}"});
            table9.AddRow(new string[] {
                        "3",
                        "public class ActivateUsers { public string Name { get;set; } }"});
            table9.AddRow(new string[] {
                        "4",
                        "public class UpdateUser { public string Name { get;set; } public Guid Id {get; se" +
                            "t; }}"});
            table9.AddRow(new string[] {
                        "5",
                        "public class CreateUser { public string Name { get;set; }}"});
#line 62
 testRunner.Given("I have written command \'ActivateUser,ActivateUsers,UpdateUser,CreateUser\' and res" +
                    "ult as:", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "CommandType",
                        "ResultType"});
            table10.AddRow(new string[] {
                        "ActivateUser",
                        "UserEntity"});
            table10.AddRow(new string[] {
                        "ActivateUsers",
                        "UserEntity"});
            table10.AddRow(new string[] {
                        "UpdateUser",
                        "UserEntity"});
            table10.AddRow(new string[] {
                        "CreateUser",
                        "UserEntity"});
#line 69
 testRunner.And("I have written command-handlers as follows:", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table11.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 77
 testRunner.When("I invoke \'UserController\' with \'Post\' method and \'CreateUserRequest\' argument:", ((string)(null)), table11, "When ");
#line 80
 testRunner.Then("CommandHandler is invoked with corresponding \'CreateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.When("I found record with id to update", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table12.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 84
 testRunner.And("I invoke \'UserController\' with \'Activate\' method and \'ActivateUserRequest\' argume" +
                    "nt:", ((string)(null)), table12, "And ");
#line 87
 testRunner.Then("CommandHandler is invoked with corresponding \'ActivateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.When("I found record with id to update", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Line",
                        "Json"});
            table13.AddRow(new string[] {
                        "1",
                        "{ \"Name\": \"John\" }"});
#line 91
 testRunner.And("I invoke \'UserController\' with \'Put\' method and \'UpdateUserRequest\' argument:", ((string)(null)), table13, "And ");
#line 94
 testRunner.Then("CommandHandler is invoked with corresponding \'UpdateUser\' argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.And("\'UserEntityResponse\' that corresponds to \'UserEntity\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
